### ISSUE TITLE
When bookmark is enabled, the textbox should be focused

### ISSUE THREAD

**Issue by kanitw** [vega/voyager2#251]
One of the participants just try to type right away.

**Comment by kanitw** [comment]
@mattwchun  This looks like a simple on to begin with. 
This would require you to look at vlplotgroup directive in the vlui repo.  
(Try setting up voyager2 and a VLUI using `bower link` so that you can update VLUI and see changes.)

**Comment by mattwchun** [comment]
@kanitw Finished this up. Here's the pull request: https://github.com/vega/vega-lite-ui/pull/293
